### ISSUE TITLE
svn add contains the parent-directory path twice in the file path.

### ISSUE THREAD

**Issue by benlazaro** [olamy/maven-scm-provider-svnjava#21]
When using this SVN provider implementation with maven-release-plugin, and using the release:prepare-with-pom, the plugin generates new files called release-pom.xml and tries to add them to SVN, but svnjava displays the following:

`SVN adding file: C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\release-pom.xml`

As you can see, the following is repeated twice:
`C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\`

This causes the plugin to fail with the following:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare-with-pom (default-cli) on project fake-driver-parent: Cannot add release POM to SCM [ERROR] Provider message: [ERROR] The svn operation failed. [ERROR] Command output: [ERROR] svn: E155010: 'C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\release-pom.xml' not found [ERROR] -> [Help 1] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare-with-pom (default-cli) on project fake-driver-parent: Cannot add release POM to SCM Provider message: The svn operation failed. Command output: svn: E155010: 'C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\release-pom.xml' not found at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212) at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120) at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355) at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155) at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584) at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216) at org.apache.maven.cli.MavenCli.main(MavenCli.java:160) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) Caused by: org.apache.maven.plugin.MojoFailureException: Cannot add release POM to SCM Provider message: The svn operation failed. Command output: svn: E155010: 'C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\release-pom.xml' not found at org.apache.maven.plugins.release.PrepareReleaseMojo.prepareRelease(PrepareReleaseMojo.java:294) at org.apache.maven.plugins.release.PrepareWithPomReleaseMojo.execute(PrepareWithPomReleaseMojo.java:47) at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132) at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208) ... 19 more Caused by: org.apache.maven.shared.release.scm.ReleaseScmCommandException: Cannot add release POM to SCM Provider message: The svn operation failed. Command output: svn: E155010: 'C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\release-pom.xml' not found at org.apache.maven.shared.release.phase.GenerateReleasePomsPhase.addReleasePomsToScm(GenerateReleasePomsPhase.java:202) at org.apache.maven.shared.release.phase.GenerateReleasePomsPhase.generateReleasePoms(GenerateReleasePomsPhase.java:134) at org.apache.maven.shared.release.phase.GenerateReleasePomsPhase.execute(GenerateReleasePomsPhase.java:108) at org.apache.maven.shared.release.phase.GenerateReleasePomsPhase.execute(GenerateReleasePomsPhase.java:95) at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:234) at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:169) at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:146) at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:107) at org.apache.maven.plugins.release.PrepareReleaseMojo.prepareRelease(PrepareReleaseMojo.java:286) ... 22 more [ERROR] [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

If I use the default SVN provider (the one installed on my machine is TortoiseSVN 1.8.15) then it works fine, which means that the default provider does take care of this issue and I'm assuming that the problem is in the svnjava provider implementation.

**Comment by benlazaro** [comment]
I forgot to mention that the fact that the parent-directory path is repeated twice in the file path, cause the plugin to fail with the following:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare-with-pom (default-cli) on project fake-driver-parent: Cannot add release POM to SCM
[ERROR] Provider message:
[ERROR] The svn operation failed.
[ERROR] Command output:
[ERROR] svn: E155010: 'C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\release-pom.xml' not
found
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare-with-pom (default-cli) on project fake-driver-parent:
 Cannot add release POM to SCM
Provider message:
The svn operation failed.
Command output:
svn: E155010: 'C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\release-pom.xml' not found
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Cannot add release POM to SCM
Provider message:
The svn operation failed.
Command output:
svn: E155010: 'C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\release-pom.xml' not found
        at org.apache.maven.plugins.release.PrepareReleaseMojo.prepareRelease(PrepareReleaseMojo.java:294)
        at org.apache.maven.plugins.release.PrepareWithPomReleaseMojo.execute(PrepareWithPomReleaseMojo.java:47)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: org.apache.maven.shared.release.scm.ReleaseScmCommandException: Cannot add release POM to SCM
Provider message:
The svn operation failed.
Command output:
svn: E155010: 'C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\C:\Users\blazaro\Documents\workspace-sts-3.8.1.RELEASE\fake-driver-parent\release-pom.xml' not found
        at org.apache.maven.shared.release.phase.GenerateReleasePomsPhase.addReleasePomsToScm(GenerateReleasePomsPhase.java:202)
        at org.apache.maven.shared.release.phase.GenerateReleasePomsPhase.generateReleasePoms(GenerateReleasePomsPhase.java:134)
        at org.apache.maven.shared.release.phase.GenerateReleasePomsPhase.execute(GenerateReleasePomsPhase.java:108)
        at org.apache.maven.shared.release.phase.GenerateReleasePomsPhase.execute(GenerateReleasePomsPhase.java:95)
        at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:234)
        at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:169)
        at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:146)
        at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:107)
        at org.apache.maven.plugins.release.PrepareReleaseMojo.prepareRelease(PrepareReleaseMojo.java:286)
        ... 22 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Comment by benlazaro** [comment]
I've tracked down the problem to be in the SvnJavaAddCommand class, line 95:
`File fileToAdd = new File( fileSet.getBasedir(), file.toString() );`

I think the code should check if the file.isAbsolutePath() is true, then `fileToAdd=file;`, otherwise do what it's doing right now.

**Comment by benlazaro** [comment]
I've updated the code to check whether `file` contains an absolute path or relative, but that is breaking some tests in the maven-scm-provider-svntest dependency, which means that maven is expecting the file be a relative path.
This concludes that the issue is not in this project but somewhere else. 
I will go ahead and close it without any modifications to the coded needed.
